### ISSUE TITLE
Final Version?

### ISSUE THREAD

**Issue by markushaslinger** [quirinecker/beam-vr#8]
Pretty sure this is not the final version of this amazing project. 😢
An anxious successor team would love to get their hands on the 'real deal' - could you please help us out here @quirinecker?

**Comment by quirinecker** [comment]
how should i or we help out?

**Comment by markushaslinger** [comment]
We (or I) would just need access to the final source code repository or simply a download of the complete zip archive. I'll take it from there, you have done enough work already 😊
Thanks in advance!

**Comment by quirinecker** [comment]
I dont have the cloud access right now, but the complete project should be on the school computer.

**Comment by markushaslinger** [comment]
Thank you for the idea, another team had modified the project on the computer already in an attempt to "play around with it", but we could salvage a lot and are confident to restore it.
